#ifndef ENGINE_PLATFORMINDEPENDENCELAYER_TIME_TIME_H_
#define ENGINE_PLATFORMINDEPENDENCELAYER_TIME_TIME_H_

namespace Turbo
{
	class Time
	{
	public:
		static double delta_time;
	};
}

#endif // ENGINE_PLATFORMINDEPENDENCELAYER_TIME_TIME_H_
